apiVersion: v1
kind: Service
metadata:
  name: {{ include "labels-injector.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "labels-injector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: labels-injector
    control-plane: controller-manager
    {{- include "labels-injector.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}