apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "labels-injector.fullname" . }}-controller-manager
  labels:
  {{- include "labels-injector.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}