apiVersion: v1
kind: Service
metadata:
  name: {{ include "labels-injector.fullname" . }}-webhook-service
  labels:
  {{- include "labels-injector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app.kubernetes.io/name: labels-injector
    control-plane: controller-manager
    {{- include "labels-injector.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}